import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import tarfile
import tempfile
import unittest
from unittest.mock import patch

from omasheets import __version__
from omasheets.errors import ConflictError
from omasheets.installation import ARCH_PACKAGES, InstallPaths, PLUGIN_ENTRY, install, source_identity, uninstall
from omasheets.integration import DESKTOP_ID, IntegrationPaths
from omasheets.native_bundle import NATIVE_EXECUTABLES, normalized_architecture, platform_id
from omasheets.user_service import UserServicePaths


ROOT = Path(__file__).resolve().parents[1]


class InstallationTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        root = Path(self.temporary.name)
        self.paths = InstallPaths(
            app=root / "data/omasheets/app",
            build=root / "cache/omasheets/native-build",
            launcher=root / "home/.local/bin/omasheets",
            service_launcher=root / "home/.local/bin/omasheets-service",
            codex_plugin=root / "home/.codex/plugins/omasheets",
            codex_marketplace=root / "home/.agents/plugins/marketplace.json",
            journal=root / "state/omasheets/installation.json",
            integration=IntegrationPaths(
                root / "data/applications" / DESKTOP_ID,
                root / "config/mimeapps.list",
                root / "state/omasheets/desktop-integration.json",
                root / "data/mime/packages/io.github.tcballard.OmaSheets.xml",
            ),
            user_service=UserServicePaths(
                root / "data/omasheets/app/bin/omasheets-service",
                root / "config/systemd/user/omasheets-native.service",
                root / "state/omasheets/user-service.json",
            ),
        )
        self.bundle = root / "omasheets-native.tar.gz"
        self.make_bundle(self.bundle)

    def tearDown(self):
        self.temporary.cleanup()

    def make_bundle(self, path, *, source=None, extra=None):
        source = source or source_identity(ROOT)
        executable = (
            "#!/bin/sh\n"
            f"printf '%s\\n' '{{\"source_commit\":\"{source['commit']}\","
            f"\"source_sha256\":\"{source['sha256']}\"}}'\n"
        ).encode()
        payloads = {f"bin/{name}": executable for name in NATIVE_EXECUTABLES}
        manifest = {
            "schema": 1,
            "version": __version__,
            "platform": platform_id(),
            "architecture": normalized_architecture(),
            "source": source,
            "files": {name: hashlib.sha256(data).hexdigest() for name, data in payloads.items()},
        }
        encoded_manifest = (json.dumps(manifest) + "\n").encode()
        with tarfile.open(path, "w:gz") as bundle:
            for name, data in {"manifest.json": encoded_manifest, **payloads, **(extra or {})}.items():
                member = tarfile.TarInfo(name)
                member.size = len(data)
                member.mode = 0o755 if name.startswith("bin/") else 0o644
                bundle.addfile(member, io.BytesIO(data))

    def test_install_and_uninstall_cover_all_owned_surfaces(self):
        result = install(ROOT, self.paths, check_dependencies=False, bundle_path=self.bundle)
        self.assertTrue(result["changed"])
        self.assertEqual(result["service_launcher"], str(self.paths.service_launcher))
        self.assertTrue(self.paths.launcher.is_file())
        self.assertTrue(self.paths.service_launcher.is_file())
        self.assertTrue((self.paths.app / "bin/omasheets-window").is_file())
        self.assertTrue((self.paths.app / "bin/omasheets-service").is_file())
        self.assertTrue((self.paths.app / "bin/omasheets-grid").is_file())
        mcp = json.loads((self.paths.codex_plugin / ".mcp.json").read_text())
        self.assertEqual(mcp["mcpServers"]["omasheets"]["command"], str(self.paths.launcher))
        marketplace = json.loads(self.paths.codex_marketplace.read_text())
        self.assertIn(PLUGIN_ENTRY, marketplace["plugins"])
        self.assertIn(str(self.paths.launcher), self.paths.integration.desktop.read_text())
        self.assertFalse(install(ROOT, self.paths, check_dependencies=False, bundle_path=self.bundle)["changed"])

        marketplace["plugins"].append({"name": "keep-me"})
        self.paths.codex_marketplace.write_text(json.dumps(marketplace))
        cache = self.paths.app / "lib/omasheets/__pycache__/generated.pyc"
        cache.parent.mkdir(exist_ok=True)
        cache.write_bytes(b"generated bytecode")
        removed = uninstall(self.paths)
        self.assertEqual(removed["conflicts"], [])
        self.assertEqual(json.loads(self.paths.codex_marketplace.read_text())["plugins"], [{"name": "keep-me"}])
        self.assertFalse(self.paths.launcher.exists())
        self.assertFalse(self.paths.service_launcher.exists())
        self.assertFalse(self.paths.codex_plugin.exists())
        self.assertFalse(self.paths.app.exists())

    def test_uninstall_accepts_a_journal_from_before_the_service_launcher(self):
        install(ROOT, self.paths, check_dependencies=False, bundle_path=self.bundle)
        journal = json.loads(self.paths.journal.read_text())
        journal.pop("service_launcher_sha256")
        self.paths.journal.write_text(json.dumps(journal))
        self.paths.service_launcher.unlink()

        removed = uninstall(self.paths)

        self.assertEqual(removed["conflicts"], [])
        self.assertFalse(self.paths.journal.exists())

    def test_explicit_environment_bundle_bypasses_automatic_release_download(self):
        with patch.dict(
            os.environ, {"OMASHEETS_NATIVE_BUNDLE_PATH": str(self.bundle)}, clear=False,
        ), patch("omasheets.installation.download_native_bundle") as download:
            result = install(ROOT, self.paths, check_dependencies=False)
        self.assertTrue(result["changed"])
        download.assert_not_called()

    def test_user_dependencies_are_runtime_only(self):
        self.assertEqual(ARCH_PACKAGES, (
            "gtk3", "libreoffice-fresh", "bubblewrap",
            "qt6-base", "qt6-declarative", "qt6-wayland",
        ))
        for build_tool in ("gcc", "make", "cmake", "pkgconf", "libreoffice-fresh-sdk"):
            self.assertNotIn(build_tool, ARCH_PACKAGES)

    def test_uninstall_preserves_a_modified_owned_file(self):
        install(ROOT, self.paths, check_dependencies=False, bundle_path=self.bundle)
        self.paths.service_launcher.write_text("user changed this")
        result = uninstall(self.paths)
        self.assertEqual(len(result["conflicts"]), 1)
        self.assertTrue(self.paths.service_launcher.exists())
        self.assertTrue(self.paths.journal.exists())

    def test_uninstall_preserves_product_when_user_service_cannot_stop(self):
        install(ROOT, self.paths, check_dependencies=False, bundle_path=self.bundle)
        with patch(
            "omasheets.installation.uninstall_user_service",
            side_effect=ConflictError("service still running"),
        ):
            result = uninstall(self.paths)
        self.assertFalse(result["changed"])
        self.assertEqual(result["conflicts"], ["service still running"])
        self.assertTrue(self.paths.app.exists())
        self.assertTrue(self.paths.launcher.exists())

    def test_launcher_quotes_shell_metacharacters_in_install_path(self):
        paths = InstallPaths(
            app=self.paths.app.with_name("app $(touch nope) 'quoted'"),
            build=self.paths.build,
            launcher=self.paths.launcher,
            service_launcher=self.paths.service_launcher,
            codex_plugin=self.paths.codex_plugin,
            codex_marketplace=self.paths.codex_marketplace,
            journal=self.paths.journal,
            integration=self.paths.integration,
            user_service=self.paths.user_service,
        )
        install(ROOT, paths, check_dependencies=False, bundle_path=self.bundle)
        launcher = paths.launcher.read_text()
        self.assertIn("'\"'\"'", launcher)
        self.assertNotIn('PYTHONPATH="', launcher)

    def test_native_service_launcher_quotes_the_private_binary_path(self):
        paths = InstallPaths(
            app=self.paths.app.with_name("app $(touch nope) 'quoted'"),
            build=self.paths.build,
            launcher=self.paths.launcher,
            service_launcher=self.paths.service_launcher,
            codex_plugin=self.paths.codex_plugin,
            codex_marketplace=self.paths.codex_marketplace,
            journal=self.paths.journal,
            integration=self.paths.integration,
            user_service=self.paths.user_service,
        )
        install(ROOT, paths, check_dependencies=False, bundle_path=self.bundle)
        launcher = paths.service_launcher.read_text()
        self.assertIn("'\"'\"'", launcher)
        self.assertIn('"$@"', launcher)
        report = json.loads(subprocess.check_output(
            [paths.service_launcher, "--provenance"], text=True,
        ))
        identity = source_identity(ROOT)
        self.assertEqual(report["source_commit"], identity["commit"])
        self.assertEqual(report["source_sha256"], identity["sha256"])

    def test_bundle_must_match_the_exact_plugin_source(self):
        wrong = self.bundle.with_name("wrong.tar.gz")
        self.make_bundle(wrong, source={"commit": "0" * 40, "sha256": "1" * 64})
        with self.assertRaisesRegex(RuntimeError, "source does not match"):
            install(ROOT, self.paths, check_dependencies=False, bundle_path=wrong)
        self.assertFalse(self.paths.app.exists())

    def test_bundle_rejects_unexpected_archive_members(self):
        unsafe = self.bundle.with_name("unsafe.tar.gz")
        self.make_bundle(unsafe, extra={"../escape": b"nope"})
        with self.assertRaisesRegex(RuntimeError, "unexpected file set"):
            install(ROOT, self.paths, check_dependencies=False, bundle_path=unsafe)
        self.assertFalse((Path(self.temporary.name).parent / "escape").exists())


if __name__ == "__main__":
    unittest.main()
